/**
 * Ubuntu NGO Platform (UNP) — module registry.
 * Every operational module is described declaratively here and rendered by
 * the generic ModuleCrud screen, so all 20+ modules share one battle-tested
 * table/form/export implementation.
 */

export type UnpFieldType =
  | 'text'
  | 'textarea'
  | 'number'
  | 'date'
  | 'select'
  | 'ref';

export interface UnpField {
  key: string;
  label: string;
  type: UnpFieldType;
  options?: string[];
  /** table + label column for foreign-key pickers */
  refTable?: string;
  refLabel?: string | string[];
  required?: boolean;
  /** show in the list table (defaults to false) */
  list?: boolean;
  badge?: boolean;
  prefix?: string;
}

export interface UnpModule {
  id: string;
  label: string;
  table: string;
  group: UnpGroup;
  icon: string;
  description: string;
  titleField: string;
  defaultSort?: { column: string; ascending: boolean };
  fields: UnpField[];
}

export type UnpGroup =
  | 'Organization'
  | 'Programme Delivery'
  | 'Enterprise Services'
  | 'Knowledge & Intelligence';

export const UNP_GROUPS: UnpGroup[] = [
  'Organization',
  'Programme Delivery',
  'Enterprise Services',
  'Knowledge & Intelligence',
];

const STATUS = (o: string[], key = 'status', label = 'Status'): UnpField => ({
  key,
  label,
  type: 'select',
  options: o,
  list: true,
  badge: true,
  required: true,
});

const DEPT: UnpField = {
  key: 'department_id',
  label: 'Department',
  type: 'ref',
  refTable: 'org_departments',
  refLabel: 'name',
  list: true,
};

const PROJECT: UnpField = {
  key: 'project_id',
  label: 'Project',
  type: 'ref',
  refTable: 'org_projects',
  refLabel: 'title',
};

const STAFF_REF = (key: string, label: string): UnpField => ({
  key,
  label,
  type: 'ref',
  refTable: 'org_staff',
  refLabel: ['first_name', 'last_name'],
});

export const UNP_MODULES: UnpModule[] = [
  // ─────────────── Organization ───────────────
  {
    id: 'departments',
    label: 'Departments',
    table: 'org_departments',
    group: 'Organization',
    icon: 'Building2',
    description: 'Organizational structure, units and their leads.',
    titleField: 'name',
    defaultSort: { column: 'display_order', ascending: true },
    fields: [
      { key: 'name', label: 'Department name', type: 'text', required: true, list: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      STATUS(['active', 'inactive']),
      { key: 'color', label: 'Colour tag', type: 'text' },
      { key: 'display_order', label: 'Display order', type: 'number' },
    ],
  },
  {
    id: 'staff',
    label: 'Human Capital',
    table: 'org_staff',
    group: 'Organization',
    icon: 'Users',
    description: 'Employees, consultants, interns and community workers.',
    titleField: 'first_name',
    defaultSort: { column: 'last_name', ascending: true },
    fields: [
      { key: 'first_name', label: 'First name', type: 'text', required: true, list: true },
      { key: 'last_name', label: 'Last name', type: 'text', required: true, list: true },
      { key: 'email', label: 'Email', type: 'text', required: true, list: true },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'position', label: 'Position', type: 'text', required: true, list: true },
      DEPT,
      {
        key: 'employment_type',
        label: 'Engagement type',
        type: 'select',
        options: ['full-time', 'part-time', 'consultant', 'volunteer', 'intern', 'board-member', 'community-worker'],
        list: true,
        required: true,
      },
      STATUS(['active', 'on-leave', 'inactive']),
      { key: 'hire_date', label: 'Start date', type: 'date' },
      { key: 'bio', label: 'Bio / skills inventory', type: 'textarea' },
      { key: 'avatar_url', label: 'Photo URL', type: 'text' },
    ],
  },
  {
    id: 'projects',
    label: 'Projects & Programmes',
    table: 'org_projects',
    group: 'Organization',
    icon: 'FolderKanban',
    description: 'Projects with objectives, budget, timeline and progress.',
    titleField: 'title',
    defaultSort: { column: 'created_at', ascending: false },
    fields: [
      { key: 'title', label: 'Project title', type: 'text', required: true, list: true },
      { key: 'description', label: 'Objectives & description', type: 'textarea' },
      DEPT,
      STATUS(['planning', 'active', 'on-hold', 'completed', 'cancelled']),
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'], list: true, badge: true, required: true },
      { key: 'start_date', label: 'Start date', type: 'date', list: true },
      { key: 'end_date', label: 'End date', type: 'date', list: true },
      { key: 'budget', label: 'Budget', type: 'number', list: true },
      STAFF_REF('project_lead_id', 'Project lead'),
      { key: 'progress', label: 'Progress %', type: 'number', list: true },
    ],
  },
  {
    id: 'workplan',
    label: 'Workplan & Activities',
    table: 'project_tasks',
    group: 'Organization',
    icon: 'ListChecks',
    description: 'Annual work plan activities feeding each project.',
    titleField: 'title',
    defaultSort: { column: 'due_date', ascending: true },
    fields: [
      { key: 'title', label: 'Activity', type: 'text', required: true, list: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'project_id', label: 'Project', type: 'ref', refTable: 'org_projects', refLabel: 'title', required: true, list: true },
      STAFF_REF('assigned_to', 'Assigned to'),
      STATUS(['todo', 'in-progress', 'review', 'done', 'blocked']),
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'], required: true, badge: true },
      { key: 'due_date', label: 'Due date', type: 'date', list: true },
      { key: 'estimated_hours', label: 'Estimated hours', type: 'number' },
      { key: 'actual_hours', label: 'Actual hours', type: 'number' },
    ],
  },

  // ─────────────── Programme Delivery ───────────────
  {
    id: 'donors',
    label: 'Donor Relationships',
    table: 'unp_donors',
    group: 'Programme Delivery',
    icon: 'HeartHandshake',
    description: 'Donor CRM: pipeline, funding history and stewardship.',
    titleField: 'name',
    defaultSort: { column: 'name', ascending: true },
    fields: [
      { key: 'name', label: 'Donor name', type: 'text', required: true, list: true },
      { key: 'donor_type', label: 'Donor type', type: 'select', options: ['institutional', 'bilateral', 'multilateral', 'foundation', 'corporate', 'individual', 'faith-based'], list: true, required: true },
      { key: 'country', label: 'Country', type: 'text', list: true },
      { key: 'contact_person', label: 'Contact person', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'relationship_status', label: 'Relationship', type: 'select', options: ['prospect', 'cultivating', 'active', 'dormant', 'closed'], list: true, badge: true, required: true },
      { key: 'total_funded', label: 'Total funded', type: 'number', list: true },
      { key: 'currency', label: 'Currency', type: 'select', options: ['USD', 'EUR', 'GBP', 'UGX', 'KES'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'grants',
    label: 'Grant Lifecycle',
    table: 'unp_grants',
    group: 'Programme Delivery',
    icon: 'FileSignature',
    description: 'Opportunity → concept → proposal → award → reporting → close-out.',
    titleField: 'title',
    defaultSort: { column: 'created_at', ascending: false },
    fields: [
      { key: 'title', label: 'Grant title', type: 'text', required: true, list: true },
      { key: 'donor_id', label: 'Donor', type: 'ref', refTable: 'unp_donors', refLabel: 'name', list: true },
      { key: 'reference_no', label: 'Reference no.', type: 'text' },
      { key: 'stage', label: 'Stage', type: 'select', options: ['opportunity', 'concept-note', 'proposal', 'submitted', 'awarded', 'contracted', 'implementation', 'reporting', 'closed', 'rejected'], list: true, badge: true, required: true },
      { key: 'amount', label: 'Amount', type: 'number', list: true },
      { key: 'currency', label: 'Currency', type: 'select', options: ['USD', 'EUR', 'GBP', 'UGX', 'KES'] },
      { key: 'submission_deadline', label: 'Submission deadline', type: 'date', list: true },
      { key: 'start_date', label: 'Start date', type: 'date' },
      { key: 'end_date', label: 'End date', type: 'date' },
      DEPT,
      PROJECT,
      { key: 'reporting_schedule', label: 'Reporting schedule', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    id: 'beneficiaries',
    label: 'Beneficiary Registry',
    table: 'unp_beneficiaries',
    group: 'Programme Delivery',
    icon: 'IdCard',
    description: 'One de-duplicated digital profile per person reached.',
    titleField: 'full_name',
    defaultSort: { column: 'created_at', ascending: false },
    fields: [
      { key: 'beneficiary_code', label: 'Beneficiary code', type: 'text', list: true },
      { key: 'full_name', label: 'Full name', type: 'text', required: true, list: true },
      { key: 'gender', label: 'Gender', type: 'select', options: ['female', 'male', 'other', 'undisclosed'], list: true },
      { key: 'date_of_birth', label: 'Date of birth', type: 'date' },
      { key: 'national_id', label: 'National ID (optional)', type: 'text' },
      { key: 'household_head', label: 'Household head', type: 'text' },
      { key: 'household_size', label: 'Household size', type: 'number' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'district', label: 'District', type: 'text', list: true },
      { key: 'village', label: 'Village', type: 'text' },
      { key: 'country', label: 'Country', type: 'text' },
      { key: 'latitude', label: 'GPS latitude', type: 'number' },
      { key: 'longitude', label: 'GPS longitude', type: 'number' },
      { key: 'programme', label: 'Programme', type: 'text', list: true },
      STATUS(['active', 'graduated', 'referred', 'exited']),
      { key: 'photo_url', label: 'Photo URL', type: 'text' },
      { key: 'notes', label: 'Support received / notes', type: 'textarea' },
    ],
  },
  {
    id: 'cases',
    label: 'Case Management',
    table: 'unp_cases',
    group: 'Programme Delivery',
    icon: 'ClipboardPlus',
    description: 'Protection, GBV, health, legal aid and livelihood cases.',
    titleField: 'case_number',
    defaultSort: { column: 'opened_date', ascending: false },
    fields: [
      { key: 'case_number', label: 'Case number', type: 'text', list: true },
      { key: 'beneficiary_id', label: 'Beneficiary', type: 'ref', refTable: 'unp_beneficiaries', refLabel: 'full_name', list: true },
      { key: 'case_type', label: 'Case type', type: 'select', options: ['child-protection', 'gbv', 'health', 'livelihoods', 'refugee', 'legal-aid', 'education', 'general'], list: true, required: true },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'], list: true, badge: true, required: true },
      STATUS(['intake', 'assessment', 'in-progress', 'referred', 'closed']),
      { key: 'opened_date', label: 'Opened', type: 'date', list: true },
      { key: 'closed_date', label: 'Closed', type: 'date' },
      STAFF_REF('assigned_to', 'Case worker'),
      DEPT,
      { key: 'summary', label: 'Case summary', type: 'textarea' },
      { key: 'action_taken', label: 'Action taken', type: 'textarea' },
      { key: 'referral', label: 'Referral', type: 'text' },
    ],
  },
  {
    id: 'indicators',
    label: 'M&E Indicators',
    table: 'unp_indicators',
    group: 'Programme Delivery',
    icon: 'Target',
    description: 'Baselines, targets and achievement against the results framework.',
    titleField: 'name',
    defaultSort: { column: 'created_at', ascending: false },
    fields: [
      { key: 'name', label: 'Indicator', type: 'text', required: true, list: true },
      PROJECT,
      { key: 'indicator_level', label: 'Level', type: 'select', options: ['input', 'activity', 'output', 'outcome', 'impact'], list: true, required: true },
      { key: 'unit', label: 'Unit of measure', type: 'text' },
      { key: 'baseline', label: 'Baseline', type: 'number', list: true },
      { key: 'target', label: 'Target', type: 'number', list: true },
      { key: 'achieved', label: 'Achieved', type: 'number', list: true },
      { key: 'frequency', label: 'Frequency', type: 'select', options: ['monthly', 'quarterly', 'biannual', 'annual'] },
      { key: 'data_source', label: 'Data source', type: 'text' },
      { key: 'disaggregation', label: 'Disaggregation', type: 'text' },
      STATUS(['on-track', 'at-risk', 'off-track', 'achieved']),
    ],
  },
  {
    id: 'measurements',
    label: 'M&E Measurements',
    table: 'unp_indicator_entries',
    group: 'Programme Delivery',
    icon: 'LineChart',
    description: 'Baseline, midline and endline data points with evidence.',
    titleField: 'period_label',
    defaultSort: { column: 'entry_date', ascending: false },
    fields: [
      { key: 'indicator_id', label: 'Indicator', type: 'ref', refTable: 'unp_indicators', refLabel: 'name', required: true, list: true },
      { key: 'period_label', label: 'Period', type: 'text', list: true },
      { key: 'entry_date', label: 'Date', type: 'date', required: true, list: true },
      { key: 'value', label: 'Value', type: 'number', required: true, list: true },
      { key: 'district', label: 'District', type: 'text', list: true },
      { key: 'evidence_url', label: 'Evidence URL', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'community',
    label: 'Community Engagement',
    table: 'unp_community_activities',
    group: 'Programme Delivery',
    icon: 'Users2',
    description: 'Meetings, trainings, savings groups, youth and women groups.',
    titleField: 'title',
    defaultSort: { column: 'activity_date', ascending: false },
    fields: [
      { key: 'title', label: 'Activity title', type: 'text', required: true, list: true },
      { key: 'activity_type', label: 'Type', type: 'select', options: ['meeting', 'training', 'awareness-campaign', 'savings-group', 'farmer-group', 'women-group', 'youth-club', 'committee'], list: true, required: true },
      { key: 'activity_date', label: 'Date', type: 'date', required: true, list: true },
      { key: 'district', label: 'District', type: 'text', list: true },
      { key: 'village', label: 'Village', type: 'text' },
      { key: 'facilitator', label: 'Facilitator', type: 'text' },
      { key: 'group_name', label: 'Group name', type: 'text' },
      { key: 'participants_total', label: 'Participants (total)', type: 'number', list: true },
      { key: 'participants_female', label: 'Participants (female)', type: 'number', list: true },
      { key: 'participants_youth', label: 'Participants (youth)', type: 'number' },
      PROJECT,
      { key: 'outcomes', label: 'Outcomes', type: 'textarea' },
      { key: 'photo_url', label: 'Photo URL', type: 'text' },
    ],
  },
  {
    id: 'field-reports',
    label: 'Field Operations',
    table: 'unp_field_reports',
    group: 'Programme Delivery',
    icon: 'MapPin',
    description: 'Field visit reports with GPS, photos and sync status.',
    titleField: 'title',
    defaultSort: { column: 'report_date', ascending: false },
    fields: [
      { key: 'title', label: 'Report title', type: 'text', required: true, list: true },
      { key: 'report_date', label: 'Date', type: 'date', required: true, list: true },
      { key: 'submitted_by', label: 'Submitted by', type: 'text', list: true },
      { key: 'district', label: 'District', type: 'text', list: true },
      { key: 'village', label: 'Village', type: 'text' },
      { key: 'latitude', label: 'GPS latitude', type: 'number' },
      { key: 'longitude', label: 'GPS longitude', type: 'number' },
      PROJECT,
      { key: 'findings', label: 'Findings', type: 'textarea' },
      { key: 'challenges', label: 'Challenges', type: 'textarea' },
      { key: 'recommendations', label: 'Recommendations', type: 'textarea' },
      { key: 'photo_url', label: 'Photo URL', type: 'text' },
      { key: 'sync_status', label: 'Sync', type: 'select', options: ['synced', 'pending', 'draft'], badge: true, list: true, required: true },
    ],
  },
  {
    id: 'partners',
    label: 'Partnerships',
    table: 'unp_partners',
    group: 'Programme Delivery',
    icon: 'Handshake',
    description: 'Government, UN, NGO, private sector and academic partners.',
    titleField: 'name',
    defaultSort: { column: 'name', ascending: true },
    fields: [
      { key: 'name', label: 'Partner name', type: 'text', required: true, list: true },
      { key: 'partner_type', label: 'Type', type: 'select', options: ['government', 'district', 'un-agency', 'ngo', 'cbo', 'private-sector', 'university', 'faith-based'], list: true, required: true },
      { key: 'country', label: 'Country', type: 'text', list: true },
      { key: 'focal_person', label: 'Focal person', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'agreement_type', label: 'Agreement type', type: 'select', options: ['mou', 'contract', 'consortium', 'informal'] },
      { key: 'agreement_start', label: 'Agreement start', type: 'date' },
      { key: 'agreement_end', label: 'Agreement end', type: 'date', list: true },
      STATUS(['active', 'pending', 'expired', 'ended']),
      { key: 'collaboration_areas', label: 'Collaboration areas', type: 'textarea' },
    ],
  },

  // ─────────────── Enterprise Services ───────────────
  {
    id: 'finance',
    label: 'Finance & Compliance',
    table: 'unp_finance_transactions',
    group: 'Enterprise Services',
    icon: 'Wallet',
    description: 'Multi-currency income and expenditure by grant and cost centre.',
    titleField: 'description',
    defaultSort: { column: 'transaction_date', ascending: false },
    fields: [
      { key: 'transaction_date', label: 'Date', type: 'date', required: true, list: true },
      { key: 'transaction_type', label: 'Type', type: 'select', options: ['income', 'expense', 'transfer', 'advance'], list: true, badge: true, required: true },
      { key: 'description', label: 'Description', type: 'text', required: true, list: true },
      { key: 'category', label: 'Category', type: 'text', list: true },
      { key: 'amount', label: 'Amount', type: 'number', required: true, list: true },
      { key: 'currency', label: 'Currency', type: 'select', options: ['UGX', 'USD', 'EUR', 'GBP', 'KES'], list: true, required: true },
      { key: 'cost_center', label: 'Cost centre', type: 'text' },
      { key: 'grant_id', label: 'Grant', type: 'ref', refTable: 'unp_grants', refLabel: 'title' },
      PROJECT,
      DEPT,
      { key: 'payment_method', label: 'Payment method', type: 'select', options: ['bank-transfer', 'mobile-money', 'cash', 'cheque', 'card'] },
      { key: 'reference_no', label: 'Reference no.', type: 'text' },
      STATUS(['recorded', 'pending', 'approved', 'reconciled', 'rejected']),
    ],
  },
  {
    id: 'procurement',
    label: 'Procurement',
    table: 'unp_procurement_requests',
    group: 'Enterprise Services',
    icon: 'ShoppingCart',
    description: 'Request → approval → tender → PO → delivery → payment.',
    titleField: 'title',
    defaultSort: { column: 'request_date', ascending: false },
    fields: [
      { key: 'request_no', label: 'Request no.', type: 'text', list: true },
      { key: 'title', label: 'Title', type: 'text', required: true, list: true },
      { key: 'description', label: 'Specification', type: 'textarea' },
      DEPT,
      STAFF_REF('requested_by', 'Requested by'),
      { key: 'stage', label: 'Stage', type: 'select', options: ['request', 'approval', 'tender', 'evaluation', 'purchase-order', 'delivery', 'inspection', 'payment', 'closed'], list: true, badge: true, required: true },
      { key: 'estimated_cost', label: 'Estimated cost', type: 'number', list: true },
      { key: 'actual_cost', label: 'Actual cost', type: 'number' },
      { key: 'currency', label: 'Currency', type: 'select', options: ['UGX', 'USD', 'EUR', 'KES'] },
      { key: 'supplier', label: 'Supplier', type: 'text', list: true },
      { key: 'request_date', label: 'Requested on', type: 'date' },
      { key: 'delivery_date', label: 'Delivery date', type: 'date', list: true },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory & Warehouse',
    table: 'unp_inventory_items',
    group: 'Enterprise Services',
    icon: 'Package',
    description: 'Relief items, medical supplies, seeds and office stock.',
    titleField: 'item_name',
    defaultSort: { column: 'item_name', ascending: true },
    fields: [
      { key: 'item_name', label: 'Item', type: 'text', required: true, list: true },
      { key: 'sku', label: 'SKU / code', type: 'text', list: true },
      { key: 'category', label: 'Category', type: 'select', options: ['medical', 'food', 'seeds', 'relief-items', 'office', 'educational', 'spare-parts', 'other'], list: true },
      { key: 'quantity', label: 'Quantity', type: 'number', required: true, list: true },
      { key: 'unit', label: 'Unit', type: 'text', list: true },
      { key: 'reorder_level', label: 'Reorder level', type: 'number', list: true },
      { key: 'warehouse', label: 'Warehouse / store', type: 'text', list: true },
      { key: 'unit_cost', label: 'Unit cost', type: 'number' },
      { key: 'expiry_date', label: 'Expiry date', type: 'date' },
      STATUS(['in-stock', 'low-stock', 'out-of-stock', 'expired']),
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'assets',
    label: 'Asset Management',
    table: 'unp_assets',
    group: 'Enterprise Services',
    icon: 'Boxes',
    description: 'Tagged assets with custodian, warranty and condition.',
    titleField: 'name',
    defaultSort: { column: 'name', ascending: true },
    fields: [
      { key: 'asset_tag', label: 'Asset tag / QR code', type: 'text', list: true },
      { key: 'name', label: 'Asset name', type: 'text', required: true, list: true },
      { key: 'category', label: 'Category', type: 'select', options: ['it-equipment', 'furniture', 'vehicle', 'machinery', 'medical', 'building', 'other'], list: true },
      { key: 'purchase_date', label: 'Purchase date', type: 'date' },
      { key: 'purchase_cost', label: 'Purchase cost', type: 'number', list: true },
      { key: 'currency', label: 'Currency', type: 'select', options: ['UGX', 'USD', 'EUR'] },
      { key: 'location', label: 'Location', type: 'text', list: true },
      STAFF_REF('custodian_id', 'Custodian'),
      DEPT,
      { key: 'condition', label: 'Condition', type: 'select', options: ['new', 'good', 'fair', 'poor', 'damaged'], list: true },
      { key: 'warranty_expiry', label: 'Warranty expiry', type: 'date' },
      STATUS(['in-use', 'in-store', 'under-repair', 'disposed', 'lost']),
      { key: 'notes', label: 'Maintenance history', type: 'textarea' },
    ],
  },
  {
    id: 'fleet',
    label: 'Fleet & Transport',
    table: 'unp_vehicles',
    group: 'Enterprise Services',
    icon: 'Truck',
    description: 'Vehicles, drivers, insurance and servicing.',
    titleField: 'plate_number',
    defaultSort: { column: 'plate_number', ascending: true },
    fields: [
      { key: 'plate_number', label: 'Plate number', type: 'text', required: true, list: true },
      { key: 'make', label: 'Make', type: 'text', list: true },
      { key: 'model', label: 'Model', type: 'text', list: true },
      { key: 'year', label: 'Year', type: 'number' },
      { key: 'vehicle_type', label: 'Type', type: 'select', options: ['4x4', 'saloon', 'van', 'truck', 'motorcycle', 'bus'], list: true },
      { key: 'assigned_driver', label: 'Assigned driver', type: 'text', list: true },
      DEPT,
      { key: 'insurance_expiry', label: 'Insurance expiry', type: 'date', list: true },
      { key: 'last_service_date', label: 'Last service', type: 'date' },
      { key: 'odometer', label: 'Odometer (km)', type: 'number' },
      STATUS(['available', 'on-trip', 'under-maintenance', 'grounded', 'disposed']),
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'trips',
    label: 'Trip Logs',
    table: 'unp_trips',
    group: 'Enterprise Services',
    icon: 'Route',
    description: 'Journey records, distance and fuel expenditure.',
    titleField: 'purpose',
    defaultSort: { column: 'trip_date', ascending: false },
    fields: [
      { key: 'vehicle_id', label: 'Vehicle', type: 'ref', refTable: 'unp_vehicles', refLabel: 'plate_number', required: true, list: true },
      { key: 'trip_date', label: 'Date', type: 'date', required: true, list: true },
      { key: 'purpose', label: 'Purpose', type: 'text', list: true },
      { key: 'origin', label: 'From', type: 'text', list: true },
      { key: 'destination', label: 'To', type: 'text', list: true },
      { key: 'driver', label: 'Driver', type: 'text' },
      { key: 'distance_km', label: 'Distance (km)', type: 'number', list: true },
      { key: 'fuel_cost', label: 'Fuel cost', type: 'number', list: true },
      STATUS(['planned', 'ongoing', 'completed', 'cancelled']),
    ],
  },
  {
    id: 'documents',
    label: 'Document Management',
    table: 'unp_documents',
    group: 'Enterprise Services',
    icon: 'FileText',
    description: 'Policies, contracts, MoUs, board papers and evaluations.',
    titleField: 'title',
    defaultSort: { column: 'created_at', ascending: false },
    fields: [
      { key: 'title', label: 'Document title', type: 'text', required: true, list: true },
      { key: 'doc_type', label: 'Type', type: 'select', options: ['policy', 'contract', 'mou', 'report', 'evaluation', 'research', 'board-paper', 'template', 'other'], list: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'file_url', label: 'File URL', type: 'text' },
      { key: 'version', label: 'Version', type: 'text', list: true },
      DEPT,
      PROJECT,
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'review_date', label: 'Next review', type: 'date', list: true },
      { key: 'confidentiality', label: 'Confidentiality', type: 'select', options: ['public', 'internal', 'restricted', 'confidential'], list: true, badge: true },
      STATUS(['draft', 'under-review', 'active', 'archived']),
    ],
  },

  // ─────────────── Knowledge & Intelligence ───────────────
  {
    id: 'knowledge',
    label: 'Learning & Knowledge',
    table: 'unp_knowledge',
    group: 'Knowledge & Intelligence',
    icon: 'BookOpen',
    description: 'Lessons learned, best practices, research and publications.',
    titleField: 'title',
    defaultSort: { column: 'published_date', ascending: false },
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, list: true },
      { key: 'knowledge_type', label: 'Type', type: 'select', options: ['lesson-learned', 'best-practice', 'success-story', 'research', 'publication', 'template', 'training-material'], list: true, required: true },
      { key: 'summary', label: 'Summary', type: 'textarea' },
      { key: 'content', label: 'Full content', type: 'textarea' },
      { key: 'author', label: 'Author', type: 'text', list: true },
      { key: 'tags', label: 'Tags', type: 'text' },
      PROJECT,
      { key: 'file_url', label: 'File URL', type: 'text' },
      { key: 'published_date', label: 'Published', type: 'date', list: true },
      STATUS(['draft', 'published', 'archived']),
    ],
  },
  {
    id: 'risks',
    label: 'Risk Register',
    table: 'unp_risks',
    group: 'Knowledge & Intelligence',
    icon: 'ShieldAlert',
    description: 'Organizational and project risks with mitigation plans.',
    titleField: 'title',
    defaultSort: { column: 'created_at', ascending: false },
    fields: [
      { key: 'title', label: 'Risk', type: 'text', required: true, list: true },
      { key: 'category', label: 'Category', type: 'select', options: ['financial', 'operational', 'security', 'compliance', 'reputational', 'programmatic', 'climate'], list: true },
      { key: 'likelihood', label: 'Likelihood', type: 'select', options: ['low', 'medium', 'high'], list: true, badge: true, required: true },
      { key: 'impact', label: 'Impact', type: 'select', options: ['low', 'medium', 'high'], list: true, badge: true, required: true },
      { key: 'mitigation', label: 'Mitigation measures', type: 'textarea' },
      { key: 'owner', label: 'Risk owner', type: 'text', list: true },
      PROJECT,
      { key: 'review_date', label: 'Review date', type: 'date', list: true },
      STATUS(['open', 'mitigating', 'monitoring', 'closed']),
    ],
  },
];

export const getModule = (id?: string) =>
  UNP_MODULES.find((m) => m.id === id);
